### ISSUE TITLE
Add more gates

### ISSUE THREAD

**Issue by cubed-guy** [cubed-guy/qutebits#2]

**Comment by AdiXgit** [comment]
assign to me

**Comment by skandesh-kk** [comment]
assign to me

**Comment by Manvith-M-Nayak** [comment]
can i get assigned?

**Comment by AdiXgit** [comment]
working on it

**Comment by taruunb** [comment]
can you please assign me to this?

**Comment by 411sst** [comment]
can i get assigned if this is still open?

**Comment by siri-n-shetty** [comment]
Could you please assign this to me?

**Comment by siri-n-shetty** [comment]
@cubed-guy I have made a pr, could you please check it

**Comment by siri-n-shetty** [comment]
@cubed-guy I have made the pr, could you check it once?
